//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValuteCourseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValuteCourse
    {
        public int NumCode { get; set; }
        public string CharCode { get; set; }
        public string ValuteName { get; set; }
        public string ValuteValue { get; set; }
    }
}
